### ISSUE TITLE
V3-Beta7 - Issues with HikVision DS-2CD2T42WD

### ISSUE THREAD

**Issue by tubalainen** [SvenVD/rpisurv#127]
Using the exact same configuration and settings the RTSP stream is very choppy in V3-Beta7 while it works great in V2-latest
The frames updates every 5-10 seconds.

display1.yaml
```
essentials:
  screens:
    - camera_streams:
        - url: "rtsp://user:pass@192.168.1.30:554/Streaming/Channels/2"
        - url: "rtsp://user:pass@192.168.1.31:554/Streaming/Channels/2"
        - url: "rtsp://user:pass@192.168.1.32:554/Streaming/Channels/2"
```

Nothing showing up in any logs. Can I active "debug" somehow?
