### ISSUE TITLE
streaming URL doesn't work

### ISSUE THREAD

**Issue by turbo2ltr** [SvenVD/rpisurv#172]
I have three Ubiquiti cameras streaming wonderfully.   I wanted to add the stream from my 3D printer camera.

If I open the command line and type `vlc http://10.0.0.110:8080/?action=stream` it opens VLC and displays the stream.

But if I add it to the rpisurv config, that camera never connects.

```
     - camera_streams:
         - url: "rtsp://10.0.0.1:7447/XXXXXXXX8B15"
           rtsp_over_tcp:  True
           freeform_advanced_vlc_options: " --rtsp-frame-buffer-size=1000000 "
         - url: "rtsp://10.0.0.1:7447/XXXXXXXXXBm8lY"
           rtsp_over_tcp:  True
           freeform_advanced_vlc_options: " --rtsp-frame-buffer-size=1000000 "
         - url: "rtsp://10.0.0.1:7447/XXXXXXXXXX4T1A"
           rtsp_over_tcp:  True
           freeform_advanced_vlc_options: " --rtsp-frame-buffer-size=1000000 "
         - url: "http://10.0.0.110:8080/?action=stream"
```
I'm not really understanding what the issue is.  As a test I changed the URL to an image on that same server and it displayed it without issue so the connectivity is there.  Any ideas?
Thanks.
