### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by stefs22** [SvenVD/rpisurv#173]
When i put my cameras, somethimes is works, somethimes is dont, somethimes just go to play and diconnect.
I try to use substream, but results its the same,
I use this on pi 4 2gb.
I try lite and full rom, change sd card etc etc, soo bad perfomanse, advice?

**Comment by SvenVD** [comment]
how many streams?

**Comment by stefs22** [comment]
My desire is 3, but it not work so i just wanted to 1 and when i make it to work i will go up for 3.
But even one rtsp or rtmp link dont work. I try rtsp, rtmp, sub, and main, just dont work.
Advices?

**Comment by SvenVD** [comment]
did you set gpu_mem to 512? What is the resolution of the streams you are trying?

**Comment by stefs22** [comment]
off course, the first think i do is make cpu mem 512, main stream is 1080p, sub is 640p.
The problem is even sub dont want to work property.
Yesterday i try my rtsp stream to vlc for 24h, and i worked all the time, so streams are good there is no question about that.

**Comment by stefs22** [comment]
i will reinstall all and try again, what is option for sound?
I want to enable on one cam, i read somewhere that something -p option, advice?

**Comment by SvenVD** [comment]
Right now i try only sub stream (640), and it show image every 5 seconds, example, 04:50.00. 04:50.05, 04:50.10 etc etc. Could you make a short movie? What is the resolution of your monitor set too? Maybe debug logs will be handy too.

Audio see https://github.com/SvenVD/rpisurv/blob/d2e1e54133f86d4c26a8bb049ae17def9deaf7db/surveillance/conf/display1.yml#L107 
But I suggest to first make your streams stable.

**Comment by SvenVD** [comment]
> Right now i try only sub stream (640), and it show image every 5 seconds, example, 04:50.00. 04:50.05, 04:50.10 etc etc. Could you make a short movie? What is the resolution of your monitor set too? Maybe debug logs will be handy too. 
The vlc which you use to test is that running the pi also? How is the pi connected, WIFI?
> 
> Audio see
> 
> https://github.com/SvenVD/rpisurv/blob/d2e1e54133f86d4c26a8bb049ae17def9deaf7db/surveillance/conf/display1.yml#L107
> 
> 
> But I suggest to first make your streams stable.

**Comment by stefs22** [comment]
its strange, now spisurv dont want to open stream, it just go black for a second and back to desktop and do this every a couple of seconds.
Its wired, screen is 1080p.
I also try displaycameras, on displaycameras every stream works, but after some time start to losing performanse and start to stutter.
I check every stream on vlc on pi, every stream works good.
![IMG_20230212_204327_678](https://user-images.githubusercontent.com/74206056/218333608-74668a94-43f1-428f-ac95-b6d3c3635899.jpg)

**Comment by SvenVD** [comment]
The only I can think of now is a problem with probing, 

Could you disable probing and try again?

https://github.com/SvenVD/rpisurv/blob/d2e1e54133f86d4c26a8bb049ae17def9deaf7db/surveillance/conf/display1.yml#L132

**Comment by stefs22** [comment]
how to see debug log?

**Comment by SvenVD** [comment]
> how to see debug log? probing is already to false: ![IMG_20230212_221321_333](https://user-images.githubusercontent.com/74206056/218337674-ff3c48dd-e094-462e-89ee-182ead0aaa32.jpg)

you should set disabling probing to true for the test, and restart

**Comment by stefs22** [comment]
```
i do this but its the same, i copy whole display file:

#THIS IS A YAML FILE, INDENTATION IS IMPORTANT. ALSO DO NOT USE TABS FOR INDENTATION, BUT USE SPACES

essentials:
  #Rpisurv will rotate over the following screens in the order they are configured here, if you only define one screen no rotation will happen

  #If you enable this option no auto rotation will happen, but you will still be able to select a screen by pressing and holding a Function Key (F1-F12) or numpad keys
  #Defaults to False
  #disable_autorotation: False

  screens:
#      #######################################################################################################
#      # Below config is included for demo and test purposes
#      # After installation you can start Rpisurv and the demo should be started
#      #######################################################################################################


     - camera_streams:
         - url: "rtsp://admin:xxxx@192.168.1.xxx:554/h264Preview_01_sub"

      -rtsp_transport tcp

#      #######################################################################################################
#      #What follows is documentation about every option that is available and where and how it can be used
#      #Below config are examples, the urls specified will not work, you need to configure your own urls.
#      #######################################################################################################
#
#      #Documentation example SCREEN 1
#      #This will show a 2x2 if all streams are connectable,
#      #Force this screen to be shown by pressing and holding F1 or keypad 0
#    - camera_streams:
#        - url: "https://images.rpisurv.net/example.png"
#          #To specify this url is not a camera stream but an image stream please set imageurl to true for this url
#          imageurl: true
#        - url: "rtsp://<user>:<password>@<ip or dnsname>:<port>/videoMain"
#          #You can also configure http or https streams like for example mjpeg streams
#        - url: "http://<ip or dnsname>:<port>/suffix"
#        - url: "rtsp://<user>:<password>@<ip or dnsname>:<port>/play1.sdp"
#
#
#      #Documentation example SCREEN 2
#      #Force this screen to be shown by pressing and holding F2 or keypad 1
#    - camera_streams:
#          #Dlink dcs-5222l example
#        - url: "rtsp://<user>:<password>@<ip or dnsname>:<port>/play1.sdp"
#
#          #OPTIONAL AND ADVANCED PER CAMERASTREAM/URL OPTIONS:
#
#          #Increase probe_timeout if you have streams that are slow to connect to. If they longer then probe_timeout seconds then rpisurv will consider them unconnectable
#          #Default to 3 seconds
#          probe_timeout: 3
#
#          #Enable this option if you want the rtsp stream to stream over tcp instead of udp, this may solve a "smearing" effect on some setups.
#          #Defaults to false
#          rtsp_over_tcp:  False
#
#          #Use the network_caching_ms option to finetune smooth playback versus stream delay
#          network_caching_ms: 500
#
#
#          #fOptional: reeform_advanced_vlc_options, most vlc options can be passed directly here.
#          #This is for advanced usage only, not all combinations have been tested
#          freeform_advanced_vlc_options: "--no-keyboard-events"
#
#          #Optional: enableaudio:
#          #To enable audio for this stream try setting this to True, the default is False
#          enableaudio: False
#
#          #Optional and advanced option: force_coordinates:
#          #If you are not happy with the pre-calculated position on the screen of a particular stream then you can override it with this option
#          #Remember that rpisurv autocalculation can also be influenced by nr_of_columns option, which is a much easier option then using force_coordinates if all you want to do is using more or less columns
#          #Note: Once you start using force_coordinates, the layout of this particular screen becomes the responsibility of the user
#          #Note2: rpisurv will continue to draw other streams with the pre-calculated values if they do not have force_coordinates set.
#          #This can cause overlap with other streams but the user can correct this by manually calculating and setting the position of the other camera streams with force_coordinates
#          #Note3: This works transparently with rotation of screens, every screen can have a different layout
#          #force_coordinates: [upperleft corner x position, upperleft corner y position, downright corner x position, downright corner y position]
#          #Example see here: https://gist.github.com/SvenVD/5c82acbb96dfb697e5e2d2420ab73ad9
#          force_coordinates: [0, 800, 600, 1080]
#          #You can use then showontop in combination with force_coordinates to create a picture in picture view (one video overlaying the other ) see demo config for example
#          showontop: False
#
#          #Foscam-fi9821w example
#        - url: "rtsp://<user>:<password>@<ip or dnsname>:<port>/videoMain"
#          #Dahua IPC-HDW4200S example or IPC-HDW4300S
#        - url: "rtsp://<user>:<password>@<ip or dnsname>:<port>/cam/realmonitor?channel=1&subtype=1"
#
#      #OPTIONAL AND ADVANCED PER SCREEN OPTIONS, YOU CAN CONFIGURE THIS PER SCREEN, IF NOT CONFIGURED A DEFAULT VALUE WILL BE USED
#
#      #NOT recommendeded to enable disable_probing_for_all_streams, it disables the removal of dead feeds which also disables auto-rearranging the screen layout.
#      #Also if using multiple screens, enabling this will slow down rotation of one screen to the next if there are unconnectable streams
#      #Defaults to False
#      disable_probing_for_all_streams: true
#
#      #How many columns you want the program to use, it will autocalculate the amount of row needed based on the resolution of your screen
#      #Default = 2
#      nr_of_columns: 2
#
#      #This is how long this screen will be shown each rotation.
#      #If this is set to a very low value then it can happen that building up the active and/or the cached screen takes longer then this duration,
#      #in that case the building and caching needs to finish first before timer will be expired and next screen is shown
#      #Defaults to 30
#      duration: 30
#
#      #Documentation example SCREEN 3
#      #This will show a 1x3 on first row + 1 stream on second row if all streams are connectable
#      #Force this screen to be shown by pressing and holding F3 or keypad 2
#    - camera_streams:
#        - url: "rtsp://<user>:<password>@<ip or dnsname>:<port>/cam/realmonitor?channel=1&subtype=1"
#        - url: "rtsp://<user>:<password>@<ip or dnsname>:<port>/videoMain"
#        - url: "http://<ip or dnsname>:<port>/suffix"
#        - url: "rtsp://<user>:<password>@<ip or dnsname>:<port>/play1.sdp"
#      nr_of_columns: 3
#
#
#      #DEFINE AS MANY SCREENS AS YOU WANT
#      #When reaching last defined screen, rotate will start at the beginning again
#      #You can have as many screens as you want, this is not limited on hardware as only the next screen will be cached ( see enable_opportunistic_caching_next_screen option in general )

```
