### ISSUE TITLE
Garbled video at higher resolution

### ISSUE THREAD

**Issue by turbo2ltr** [SvenVD/rpisurv#179]
I've been running three Unifi cameras on a 1080 monitor without issue for years. The streams I use were the "medium" streams (1280x720)

I upgraded to a larger 4K monitor so I went to change the stream to the "high" stream (2688x1512) and I get what you see in the top left.  

![20231120_214139](https://github.com/SvenVD/rpisurv/assets/10290656/2a1c54b5-d9ac-4dd3-9d3b-a777e1a09651)

The main darker area looks like it "scrolls" up. Like every time the frame is drawn it's drawn one pixel off.  The green part on the right side of the frame is a repeating pattern of random garbage.

Opening the same stream in VLC works fine.

```
- camera_streams:
         - url: "rtsp://10.0.0.1:7447/xxx"
           rtsp_over_tcp:  True
           freeform_advanced_vlc_options: " --rtsp-frame-buffer-size=1000000"
           force_coordinates: [0, 0, 1920,1080 ]
```

Any suggestions?
